controller_manager:
  ros__parameters:
    update_rate: 50  # Hz, can adjust to simulation speed

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_cont:
      type: diff_drive_controller/DiffDriveController
      left_wheel_names: ["left_wheel_joint"]
      right_wheel_names: ["right_wheel_joint"]
      publish_rate: 50.0
      cmd_vel_timeout: 0.5
      use_stamped_vel: false

      # Wheel geometry
      wheel_separation: 0.21        # distance between wheels [m]
      wheel_radius: 0.05            # radius of wheels [m]

      # Frame IDs
      base_frame_id: base_link
      odom_frame_id: odom

      # Odometry settings
      enable_odom_tf: true
      publish_wheel_data: true
      open_loop: false
