controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters: {}

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.1515
    wheel_radius: 0.033
    publish_rate: 50.0
    use_stamped_vel: false
    cmd_vel_timeout: 0.5
    base_frame_id: "base_link"
    enable_odom_tf: true
    publish_state: true   
